// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCP07thjfjnWP4q-cuuVeEIZuDdY0JBT1Y',
    appId: '1:553309232729:web:d8aeec8b0bb25744c6db48',
    messagingSenderId: '553309232729',
    projectId: 'emotion-dairy-5aab7',
    authDomain: 'emotion-dairy-5aab7.firebaseapp.com',
    storageBucket: 'emotion-dairy-5aab7.firebasestorage.app',
    measurementId: 'G-CD9FDYCT9J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB43UNMsMurztmc46LOrYDotFGTyLgX7gM',
    appId: '1:553309232729:android:908721f4b6c087a9c6db48',
    messagingSenderId: '553309232729',
    projectId: 'emotion-dairy-5aab7',
    storageBucket: 'emotion-dairy-5aab7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAO9xmOmqARDS6PgWDuCJWSm00Dudikrn8',
    appId: '1:553309232729:ios:c198c3eac55bdf83c6db48',
    messagingSenderId: '553309232729',
    projectId: 'emotion-dairy-5aab7',
    storageBucket: 'emotion-dairy-5aab7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAO9xmOmqARDS6PgWDuCJWSm00Dudikrn8',
    appId: '1:553309232729:ios:c198c3eac55bdf83c6db48',
    messagingSenderId: '553309232729',
    projectId: 'emotion-dairy-5aab7',
    storageBucket: 'emotion-dairy-5aab7.firebasestorage.app',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCP07thjfjnWP4q-cuuVeEIZuDdY0JBT1Y',
    appId: '1:553309232729:web:610f8794c1b0a138c6db48',
    messagingSenderId: '553309232729',
    projectId: 'emotion-dairy-5aab7',
    authDomain: 'emotion-dairy-5aab7.firebaseapp.com',
    storageBucket: 'emotion-dairy-5aab7.firebasestorage.app',
    measurementId: 'G-NRNSS90MBT',
  );

}